# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CMChatBubble' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CMChatBubble

  pod 'RealmSwift', '~> 3.12.0', :modular_headers => true

  target 'CMChatBubbleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CMChatBubbleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
